version: '3.5'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=password
     - POSTGRES_DB=db
    volumes:
      - ./db:/var/lib/postgresql/data
  redis:
    image: redis
    depends_on:
     - db
    volumes:
     - ./cache:/data
  backend-docker:
    image: backend-docker
    depends_on:
     - db
     - redis
    environment:
     #- FRONT_URL=http://localhost:5000
     - REDIS=redis
     - DB_NAME=db
     - DB_USERNAME=postgres
     - DB_PASSWORD=password
     - DB_HOST=db
  front-docker:
    image: front-docker
    environment:
     - API_URL=http://localhost/api
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./ng/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - front-docker
      - backend-docker
