version: '3.5'

services:
  redis:
    image: redis
    ports:
     - 127.0.0.1:6379:6379
  backend-docker:
    image: backend-docker
    ports:
     - 127.0.0.1:8000:8000
    environment:
     - FRONT_URL=http://localhost:5000
     - REDIS=redis
  front-docker:
    image: front-docker
    ports:
     - 127.0.0.1:5000:5000
    environment:
     - API_URL=http://localhost:8000
