version: '3.5'

services:
  db:
    image: postgres
    ports:
      - 127.0.0.1:5432:5432
    restart: unless-stopped
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=password
     - POSTGRES_DB=db
    volumes:
      - database:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
     - 127.0.0.1:6379:6379
    depends_on:
     - db
  backend-docker:
    image: backend-docker
    ports:
     - 127.0.0.1:8000:8000
    depends_on:
     - db
     - redis
    environment:
     - FRONT_URL=http://localhost:5000
     - REDIS=redis
     - DB_NAME=db
     - DB_USERNAME=postgres
     - DB_PASSWORD=password
     - DB_HOST=db
  front-docker:
    image: front-docker
    ports:
     - 127.0.0.1:5000:5000
    environment:
     - API_URL=http://localhost:8000

volumes:
  database: